In [91]:
import torch
import tiktoken

In [92]:
raw_text = "This is my dog Raylan"

In [93]:
tokenizer = tiktoken.get_encoding("gpt2")

In [94]:
enc_text = tokenizer.encode( raw_text )
print(enc_text)

[1212, 318, 616, 3290, 7760, 9620]


In [95]:
vocab_size = 5
output_dim = 4
inputs = torch.nn.Embedding( vocab_size, output_dim )
print( inputs.weight )


Parameter containing:
tensor([[ 2.0054,  0.8437, -0.1893, -1.1401],
        [-1.0140, -0.9595,  0.7667, -0.2105],
        [-0.6968, -1.4435, -1.7641,  0.2957],
        [ 1.2166, -0.9692,  0.1643,  0.6286],
        [-0.1367, -1.5283,  0.4057, -0.0591]], requires_grad=True)


In [96]:
inputs = inputs.weight.data
print(inputs)


tensor([[ 2.0054,  0.8437, -0.1893, -1.1401],
        [-1.0140, -0.9595,  0.7667, -0.2105],
        [-0.6968, -1.4435, -1.7641,  0.2957],
        [ 1.2166, -0.9692,  0.1643,  0.6286],
        [-0.1367, -1.5283,  0.4057, -0.0591]])


In [97]:
inputs.shape

torch.Size([5, 4])

In [98]:
for row in inputs:
    print(row.tolist())

[2.0053961277008057, 0.8436736464500427, -0.18932749330997467, -1.140106201171875]
[-1.0140067338943481, -0.9595248103141785, 0.766706645488739, -0.21046698093414307]
[-0.6968480944633484, -1.4434772729873657, -1.7640630006790161, 0.295712947845459]
[1.2166022062301636, -0.9692355394363403, 0.16427280008792877, 0.6286182999610901]
[-0.13672968745231628, -1.528276801109314, 0.405729204416275, -0.05911269411444664]


In [99]:
x = torch.Tensor([1.1,2.3])
y = torch.Tensor([3.4,-2.1])

In [100]:
1.1*3.4 + 2.3*-2.1

-1.0899999999999999

In [101]:
torch.dot(x,y)

tensor(-1.0900)

In [ ]:
query = inputs[2]
print(query)

tensor([-0.6968, -1.4435, -1.7641,  0.2957])


In [107]:
for i in range( len( inputs )):
    print( torch.dot(query, inputs[i]))

tensor(-2.6184)
tensor(0.6769)
tensor(5.7686)
tensor(0.4474)
tensor(1.5681)


In [111]:
attention_scores_2 = torch.zeros(len(inputs))
for i in range( len( inputs )):
    attention_scores_2[i] = torch.dot(query, inputs[i])
print(attention_scores_2)

tensor([-2.6184,  0.6769,  5.7686,  0.4474,  1.5681])


In [ ]:
# #normalize the attention scores using the softmax function
# def softmax(x):
#     torch.exp(x) / torch.exp(x).sum()

In [120]:
attention_scores_2 = torch.softmax(attention_scores_2, dim = 0)
print(attention_scores_2)
print( attention_scores_2.sum() )

tensor([0.1892, 0.1894, 0.2423, 0.1894, 0.1897])
tensor(1.)


In [123]:
context_vector_2 = torch.zeros( query.shape )
for i in range(len(attention_scores_2)):
    context_vector_2 += attention_scores_2[i]*inputs[i]
print(context_vector_2)

tensor([ 0.2231, -0.8452, -0.2100, -0.0761])
