In [1]:
import torch
import tiktoken

In [2]:
with open ("one-foggy-night.txt", "r" ) as f:
    raw_text = f.read()

print (raw_text[:50])

A PLUME of smoke drifted under the great glass dom


In [3]:
tokenizer = tiktoken.get_encoding("gpt2")

In [4]:
enc_text = tokenizer.encode(raw_text)

In [5]:
print(enc_text[:20])

[32, 9297, 38340, 286, 7523, 38648, 739, 262, 1049, 5405, 29500, 286, 3454, 363, 17913, 9327, 355, 262, 8342, 10604]


In [6]:
print( tokenizer.decode( enc_text[:2]))
len( enc_text)

A PL


5513

In [7]:
for i in range(1,10):
    print("Input:", tokenizer.decode(enc_text[:i]), "Target:", tokenizer.decode([enc_text[i]]))

Input: A Target:  PL
Input: A PL Target: UME
Input: A PLUME Target:  of
Input: A PLUME of Target:  smoke
Input: A PLUME of smoke Target:  drifted
Input: A PLUME of smoke drifted Target:  under
Input: A PLUME of smoke drifted under Target:  the
Input: A PLUME of smoke drifted under the Target:  great
Input: A PLUME of smoke drifted under the great Target:  glass


In [8]:
print("PyTorch version:", torch.__version__)

PyTorch version: 2.2.2


In [9]:
from torch.utils.data import Dataset, DataLoader


class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
        assert len(token_ids) > max_length, "Number of tokenized inputs must at least be equal to max_length+1"

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [10]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [11]:
with open("one-foggy-night.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [12]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=4, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[   32,  9297, 38340,   286]]), tensor([[ 9297, 38340,   286,  7523]])]


In [13]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[ 7523, 38648,   739,   262]]), tensor([[38648,   739,   262,  1049]])]


In [14]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   32,  9297, 38340,   286],
        [ 7523, 38648,   739,   262],
        [ 1049,  5405, 29500,   286],
        [ 3454,   363, 17913,  9327],
        [  355,   262,  8342, 10604],
        [ 1625,  6364,   284,   257],
        [ 1302, 24219,    13,   632],
        [  373,  1972,  2739,   783]])

Targets:
 tensor([[ 9297, 38340,   286,  7523],
        [38648,   739,   262,  1049],
        [ 5405, 29500,   286,  3454],
        [  363, 17913,  9327,   355],
        [  262,  8342, 10604,  1625],
        [ 6364,   284,   257,  1302],
        [24219,    13,   632,   373],
        [ 1972,  2739,   783,    11]])


In [15]:
#get the dimensions and type of the input
print(type(inputs))
print(inputs.shape)

<class 'torch.Tensor'>
torch.Size([8, 4])


In [16]:
# look at the first row
inputs[0]

tensor([   32,  9297, 38340,   286])

In [17]:
# look at the first column, or the first element of each row
inputs[:,0]

tensor([  32, 7523, 1049, 3454,  355, 1625, 1302,  373])

In [18]:
# iterating through the tensors, looking at the words rather than the tokens 
for row in inputs:
    print(tokenizer.decode ( row.tolist()))

A PLUME of
 smoke drifted under the
 great glass dome of
 Slagborough Station
 as the Northern Express
 came slowly to a
 standstill. It
 was getting late now


In [19]:

with open("one-foggy-night.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False)
data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)
second_batch = next(data_iter)
print(second_batch)

[tensor([[   32,  9297, 38340,   286]]), tensor([[ 9297, 38340,   286,  7523]])]
[tensor([[ 9297, 38340,   286,  7523]]), tensor([[38340,   286,  7523, 38648]])]


In [20]:
vocab_size = 6
output_dim = 3

In [21]:
embedding = torch.nn.Embedding( vocab_size, output_dim )

In [22]:
print(embedding.weight)

Parameter containing:
tensor([[-0.6581, -0.5634, -0.2210],
        [ 0.1127, -0.8773, -0.7109],
        [-0.2395,  0.0193,  1.8225],
        [-0.6451,  0.4337,  2.5604],
        [ 0.0647,  0.9500,  0.5294],
        [-1.2725, -0.1775,  1.0687]], requires_grad=True)


In [23]:
#get rid of the requires_grad bit value
embedding.weight.data

tensor([[-0.6581, -0.5634, -0.2210],
        [ 0.1127, -0.8773, -0.7109],
        [-0.2395,  0.0193,  1.8225],
        [-0.6451,  0.4337,  2.5604],
        [ 0.0647,  0.9500,  0.5294],
        [-1.2725, -0.1775,  1.0687]])

In [24]:
# or get rid of the ..
print(embedding.weight.detach())

tensor([[-0.6581, -0.5634, -0.2210],
        [ 0.1127, -0.8773, -0.7109],
        [-0.2395,  0.0193,  1.8225],
        [-0.6451,  0.4337,  2.5604],
        [ 0.0647,  0.9500,  0.5294],
        [-1.2725, -0.1775,  1.0687]])


In [25]:
embeddingb = torch.nn.Embedding( tokenizer.n_vocab, 256)

In [26]:
embeddingb.weight

Parameter containing:
tensor([[ 1.0801,  0.9704, -1.4465,  ..., -1.0361,  1.5483, -0.8087],
        [ 0.6358,  0.8066, -0.3688,  ..., -2.4138,  2.2698, -0.8626],
        [ 0.3924, -0.1876,  0.6837,  ...,  1.7041, -0.7503, -0.9759],
        ...,
        [-0.8264,  0.9193,  1.8463,  ...,  0.1582, -0.4945, -0.9616],
        [-1.0001,  0.0571, -0.1649,  ...,  0.6863,  0.3031,  0.9207],
        [ 0.1611,  0.8415, -0.4835,  ..., -1.9034,  1.1451,  0.7738]],
       requires_grad=True)

In [27]:
# make a tensor from scratch from scratch
x = torch.tensor([2.2,1.5])
y = torch.tensor([1.4,2.3])
print(x,y)

tensor([2.2000, 1.5000]) tensor([1.4000, 2.3000])


In [28]:
torch.dot(x,y)

tensor(6.5300)